### ISSUE TITLE
Text is doubling up in editor

### ISSUE THREAD

**Issue by AutomationMan808** [danpros/htmly#566] opened 2022-06-29 22:15 UTC
v2.8.2

I'm working on a sales page. As I scroll down the wysiwyg I notice repeats of text which I did not place in there. This happens after saving as draft then reopening.

**Comment by danpros** [comment] 2023-12-16 12:25
Hello, 

I can't reproduce it. I will close this one. If the problems still persist please open new issue. Thanks.

**Closed by danpros** 2023-12-16 12:25 UTC
