### ISSUE TITLE
[BUG REPORT]  /admin/categories/my-category

### ISSUE THREAD

**Issue by cuixiping** [danpros/htmly#821] opened 2024-10-08 13:12 UTC
**Describe the bug**

`category` in the slug will be replaced with `admin/categories` in the category link of posts list page on admin panel.

The reason is that PHP `str_replace` function will replace all matches, but here only should replace once.

`<?php echo str_replace('category', 'admin/categories', $p->categoryUrl); ?>`
should be
`<?php echo preg_replace('@category@', 'admin/categories', $p->categoryUrl, 1); ?>`

**To Reproduce**

1. Create a category which title is `My category`, and slug is `my-category`.
2. Create a post within the `My category`.
3. On `Posts list` page, click `My category` on the category column.

**Expected behavior**
Show posts in the category of `My category`.
Page url should be `/admin/categories/my-category`

**Screenshots/Errors**
Page url will go to `/admin/categories/my-admin/categories`, and 404 error occurs.

**HTMLy Version**
v3.0.0

**Server Info (please complete the following information):**
 - Ubuntu 22.04.4
 - Apache 2.4
 - PHP 8.3

**Comment by Joduai** [comment] 2024-10-08 16:27
I'm on somewhat latest version from repo thus I cannot reproduce.  
Could you download latest code and confirm that this bug still occurs?

**Comment by danpros** [comment] 2024-10-08 16:32
Thanks for reporting it, yes its confirmed. Simple fix using:

```
<td><a href="<?php echo site_url() . 'admin/categories/' . $p->categorySlug; ?>"><?php echo strip_tags($p->category);?></a></td>
```

@Joduai the problems only show up if the category URL contains `category` string.

This will fixed in next release.

**Comment by danpros** [comment] 2024-10-08 16:51
This has been fixed in master branch

**Comment by danpros** [comment] 2024-10-13 22:10
This has been fixed in latest release. Thanks

**Closed by danpros** 2024-10-13 22:10 UTC
Labels: bug
