### ISSUE TITLE
draft posts pooled after common publish article click

### ISSUE THREAD

**Issue by Aar-Noma** [danpros/htmly#789] opened 2024-08-08 12:49 UTC
**Describe the bug**
draft posts pooled after common publish article click

**To Reproduce**
create new article, publish it and after some time this is in drafts, if you publish these drafts, you have 2 equal articles, the problem is previous shared links, if you delete wrong article of doubles every user loses previous links on article

**Expected behavior**
after publish article not in drafts again

**Screenshots/Errors**
If applicable, add screenshots and/or error messages to help explain your problem. You may need to check your webserver's error logs.

**HTMLy Version**
2.9.9

**Server Info (please complete the following information):**
 - OS: red hat linux 8.9 webhosting webzdarma.cz
 - Webserver: apache
 - PHP Version PHP 8.2

**Comment by danpros** [comment] 2024-08-09 00:51
Hello,

The auto save enabled? The article has the same title?

**Comment by danpros** [comment] 2024-08-09 00:54
Please test it again and be more clear (provide step by step) because I can't reproduce it.

**Comment by Aar-Noma** [comment] 2024-08-09 08:29
yes, **autosave is on**, article had the **same name**, articles were **ordered in Drafts** queue, what was more, one of them was **impossible to publish from drafts**, only stuck there, so I **clicked delete article**.. ones of such examples was: [](https://hrubos.org/blog/search/tsar) I made both articles public. One had my **own slug**, another one had [autoslug](url). What is more server is having some strange behaviour, do you think my provider had been **invaded by hackers?** Attaching pics:

![tu_nieco_nesedi](https://github.com/user-attachments/assets/f175ad9b-e429-41df-a9c9-b78df4d453d9)

![tu_nieco_nesedi2](https://github.com/user-attachments/assets/b71675e7-c9e5-4d02-80f4-519feba298c6)

**Comment by danpros** [comment] 2024-08-09 11:10
The problem seems due to the post having the same slug. So it doesn't matter whether you use a custom slug or automatic, if the slug is the same then problems will arise.

Currently when creating a slug from title, htmly tries to check if the slug already exists and if it is already in use it will add the date timestamp after the slug. example: `/post/already-used-slug` become `/post/already-used-slug-201408085034`

This is not a bug but current htmly limitation because when editing the posts etc. it search for file that match the slug. In the future it can be developed further, for example by matching the categories, tags, author etc.

For server problems you should read the server log or contact/open ticket to your hosting provider.

**Comment by danpros** [comment] 2024-08-10 02:50
So what is the solution without deleting the post? Just edit the post and change the slug and save. The problem should no longer occur because both posts now have different slugs.

**Comment by danpros** [comment] 2024-10-13 22:10
This has been fixed in latest release. Thanks

**Closed by danpros** 2024-10-13 22:10 UTC
Labels: support
