### ISSUE TITLE
Escaped backslashes removed when editing posts.

### ISSUE THREAD

**Issue by NiccyB** [danpros/htmly#601] opened 2023-01-04 08:52 UTC
v2.8.2, replicated on multiple platforms.

Consider the following post:
`You should see a backslash here --> '\\'`
This correctly displays: "You should see a backslash here --> '\\'"
When it is opened for editing, the code changes and one of the backslashes is removed:
`You should see a backslash here --> '\'`
If the post is edited again (without the missing backslash being re-inserted), another backslash is removed:
`You should see a backslash here --> ''`

**Comment by NiccyB** [comment] 2023-01-04 08:52
This also applies to the post's title and meta description.

**Comment by JPLeRouzic** [comment] 2023-01-04 09:11
It was reported 6 months ago.
I wrote where the problem was and it was confirmed by @recolic.
It is because the use of the function stripslashes() in add_content() and edit_content().
Presumably it was copied from a code snippet on Internet that was intended to be used when coping with data from a database.
In [my own code](https://github.com/JPLeRouzic/Coralie/) I left this, I should remove ASAP.

**Comment by NiccyB** [comment] 2023-01-04 09:25
Ah, apologies. I did search, but I've just realised I searched a different project I was working on. d'Oh!

**Comment by JPLeRouzic** [comment] 2023-01-04 09:30
No need for apologies :-)

**Comment by danpros** [comment] 2023-12-01 14:19
I will close this one.

Thanks,

**Closed by danpros** 2023-12-01 14:19 UTC
