### ISSUE TITLE
error uploading image: "undefined"

### ISSUE THREAD

**Issue by ProjectPatatoe** [danpros/htmly#442] opened 2021-03-12 22:37 UTC
* version 2.7.9
* apache2
1. regular post
2. insert image
3. pop up shows up with "undefined"
![image](https://user-images.githubusercontent.com/27925441/111005614-02059d00-8340-11eb-860d-150fd54ba6e3.png)

upload does work. upload.php returns with
```json
{
"path":"content\/images\/20210312143351-testimg.png",
"name":"testimg.png",
"error":0
}
```
the file is in fact uploaded and found in `content/images/20210312143351-testimg.png`

there is no error in the apache log

**Comment by danpros** [comment] 2021-03-12 23:51
Hello,

I can't reproduce it, did you put eg. `if (!defined('HTMLY')) die('HTMLy');` let say in upload.php?

**Comment by ProjectPatatoe** [comment] 2021-03-13 01:08
I didn't modify any files, Only the configs.

**Comment by danpros** [comment] 2021-03-13 01:38
@ProjectPatatoe please go to /system/admin/views directory and edit the `add-content.html.php` and try to remove the `if (!defined('HTMLY')) die('HTMLy');` let see if the problems still exist or not.

**Comment by ProjectPatatoe** [comment] 2021-03-13 02:06
Still same problem. Unable to upload an image.
I noticed that if I specify a url instead, works as expected. I also then manually changed the address to point to the uploaded image, its shows correctly.

**Comment by ProjectPatatoe** [comment] 2021-03-13 04:22
Ok I have narrowed down the error. It only happens in Firefox, and not in Chrome or IE. The problem is in `system/admin/editor/js/jquery.ajaxfileupload.js` [line 110](https://github.com/danpros/htmly/blob/b1b6352c62644a0136966054692bd5e80106a722/system/admin/editor/js/jquery.ajaxfileupload.js#L110)
```js
            var response, responseStr = $(loadedFrame).contents().text();
```
Specifically the .text() is different from Chrome. Seems like a bug either in Firefox or Jquery. I've made a PR with the fix that is tested in Firefox, Chrome, IE, Firefox for mobile. PR #444

**Comment by danpros** [comment] 2021-03-13 05:27
Great thank you, perhaps specific FF version because its work fine from me. I use FF 86.0.1

**Comment by ProjectPatatoe** [comment] 2021-03-13 08:55
Hm strange. I am also on FF 86.0.1 . The only thing left i can think of is extensions then. May need to keep this in mind if something weird happens again like this. I disabled uBlock origin but no change.

**Comment by danpros** [comment] 2021-03-24 10:41
Hello, I will close this one because your pull request. Thanks,

**Comment by xanathon** [comment] 2021-03-29 13:43
I have the same problem in Vivaldi 2.11.1811.38 (Stable channel)

**Comment by danpros** [comment] 2021-03-29 13:58
Hello, please use the latest source code https://github.com/danpros/htmly/archive/refs/heads/master.zip

This version not released yet.

**Comment by xanathon** [comment] 2021-03-29 14:37
I was under the impression that the autoinstaller should pull the latest version.

How do I install the latest version? Just overwrite the files that are there now?

Thanks.

**Comment by danpros** [comment] 2021-03-29 14:47
Yes you just need to rewrite it, but if you want to use non development version you can download this https://raw.githubusercontent.com/danpros/htmly/34e0058c23c8c91b800e7ddfff079bb04ca4f5d1/system/admin/editor/js/jquery.ajaxfileupload.js and than put it in `system/admin/editor/js` folder (replace the `jquery.ajaxfileupload.js` with it).

**Comment by xanathon** [comment] 2021-03-29 18:09
thanks, works.

**Comment by danpros** [comment] 2021-04-01 13:57
This should has been fixed in latest release. Thanks,

**Closed by danpros** 2021-04-01 13:57 UTC
Labels: bug
